name: Publish JavaScript Client
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish package to NPM
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./clients/javascript

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set package.json version
        run: npm version --no-git-tag-version $(git describe --always --dirty --tags --abbrev=0)

      - name: Publish
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
